# Generated by Django 5.2.3 on 2025-07-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_progressupdate_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='name',
            field=models.CharField(default='Skill_Name', max_length=100),
            preserve_default=False,
        ),
    ]
