# Generated by Django 5.2.3 on 2025-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 6:00:00.000000'),
            preserve_default=False,
        ),
    ]
