# Generated by Django 5.2.3 on 2025-07-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_profile_created_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_add',
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 06:00:00+0800'),
            preserve_default=False,
        ),
    ]
